[package]
name = "qr_generator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
qrcode-generator = "4.1.9"

[[bin]]
name = "qr_generator"
path = "main.rs"
